### PR TITLE
update Docker env path

### PR DESCRIPTION
**Pull request by lpantano**
Sorry forgot to update the Docker with the new version number. 

I am working on the main PR once I get the docker image with the correct software ...Thanks

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [x] `CHANGELOG.md` is updated
 
**Learn more about contributing:** https://github.com/nf-core/smrnaseq/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by lpantano** [comment]
I will test this first locally, I forgot I could do this :s hold onto this. Thanks

**Comment by ewels** [comment]
It’s better not to update version numbers manually if possible, but to use `nf-core bump-version` as they are littered all over the place..

The command runs linting first, so you might need to downgrade a version or two to get to one where the linting passes so that you can bump the versions.

**Comment by lpantano** [comment]
ok, I got to run docker build locally. A lot of issues using the latest version of everything so I needed to downgrade a bunch.

Ready to go.

**Comment by lpantano** [comment]
I run bump-versions, but for this branch I only got these files. I can do the full PR, and re-start travis after Docker gets build if that works better. nf-core lint is working, some warning bc not all the packages are updated to the latest...

**Pull request merged**
