### PR TITLE
Allow a gene to have reads in all samples in the edgeR analysis

### PR DESCRIPTION
**Pull request by sdjebali**
This PR is to allow a gene to have reads in all samples in the edgeR analysis step

- [x] This comment contains a description of changes (with reason).
- [x] Make sure your code lints (`nf-core lint .`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [x] `CHANGELOG.md` is updated.

### CODE REVIEW

**Comment by lpantano** [comment]
@sdjebali , This seems pretty good, maybe update the changelog file with the reason to make the change?

**Review by ewels — APPROVED** [review]
Looks good! Just needs an update to `CHANGELOG.md`.

I updated the PR body text, removing the parts of the checklist that are not relevant.

**Comment by sdjebali** [comment]
done

**Review by JoseEspinosa — APPROVED** [review]
LGTM 👍

**Comment by lpantano** [comment]
@ewels, do you think we can merge this even if nf-core linting is failing? I guess is because we didn't merge the with the current TEMPLATE. What would you recommend? Thanks!

**Comment by JoseEspinosa** [comment]
Thanks @lpantano and @ewels I forget to add a similar comment, I wanted to check the template merge but was busy these days 😓

**Comment by hmkim** [comment]
In my real case, I meet the same situation.
 Please consider this commit.

**Comment by lpantano** [comment]
Hi,

can you explain further. This is already part of the dev branch. Are you seeing the same issue with this branch or the master?

**Pull request merged**
