### PR TITLE
Pipeline update / Manual template merge

### PR DESCRIPTION
**Pull request by ewels**
* Manually merged the three new template updates and fixed all merge conflicts.
* Moved all parameter documentation into new `nextflow_schema.json` file.
* Renamed `--reads` to `--input` to match new nf-core guidelines.
* Updated `CamelCase` and `Upper Case` parameters to be `lower_case_snake_case`
* Changed dev version from `1.0.1` to `1.1` as now has fairly major changes.

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [x] Make sure your code lints (`nf-core lint .`).
 - [x] Documentation in `docs` is updated
 - [x] `CHANGELOG.md` is updated
 - [x] `README.md` is updated

### CODE REVIEW

**Comment by ewels** [comment]
Merging this PR should auto-merge / close https://github.com/nf-core/smrnaseq/pull/51 without needing any additional actions.

**Comment by ewels** [comment]
Looks like we have some conda package conflicts 😞

I don't think I have caused these, so assuming that the tests were passing before, I guess that this is an upstream change.

**Comment by ewels** [comment]
NB: This PR will need updating if/when https://github.com/nf-core/smrnaseq/pull/42 is merged..

**Comment by ewels** [comment]
Ok, I think that this PR is good to go now 🚀 

Tests should all be passing, no additional content to update before merge that I'm aware of ✅ 

Just need a 👍🏻 review and merge.

**Review by lpantano — APPROVED** [review]

**Pull request merged**
