### PR TITLE
Fix igenomes_base in nextflow_schema

### PR DESCRIPTION
**Pull request by nschcolnicov**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/smrnaseq/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/smrnaseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core pipelines lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by nschcolnicov** [comment]
Removed the igenomes_base from the nextflow schema, not sure why the CI test checking if the PR is pointing towards dev is failing, should be ok

**Review by mashehu — COMMENTED** [review]
Are you not using igenomes?

**Comment by nschcolnicov** [comment]
> Are you not using igenomes?

Yes we are, igenomes_base was added into the nextflow_schema as a quickfix, I'm reverting this fix which is no longer needed. With the recent update in the nf-core template, the parameters from schema ignore were not being properly parsed, making the linting fail due to not seeing an entry for the igenomes_base parameter in the nextflow_schema. This was already patched, so we no longer need to have the igenomes_base entry in the nextflow_schema

**Comment by mashehu** [comment]
but if you use igenomes, why don't you want to use `igenomes_base`? it is a standard param when including igenomes in the template.

**Review by mashehu — APPROVED** [review]

**Comment by nschcolnicov** [comment]
@mashehu Should be good to go now, let me know if you have any comments

**Pull request merged**
