### PR TITLE
fix manifest information

### PR DESCRIPTION
**Pull request by lpantano**
fixing manifest to match dev

https://github.com/nf-core/smrnaseq/issues/17

@drpatelh is that what you meant?

### CODE REVIEW

**Comment by drpatelh** [comment]
@lpantano Exactly! To be honest, Im not sure how much it matters but as its mentioned in the `docs` its best to be safe than sorry.

**Comment by drpatelh** [comment]
Travis CI is failing for a number of weird and wonderful reasons. The `markdownlint` error will be the easiest to fix. 

I havent seen those linting errors before @sven1103 @apeltzer is this expected because the tests are running on the `TEMPLATE` branch? Im assuming they werent set up for this purpose. Do we need to integrate this into `tools` somehow?

The pipeline failure is down to that weird behaviour @apeltzer noticed yesterday which will probably just require a re-trigger when things are working again.

**Comment by drpatelh** [comment]
@lpantano Those weird Travis errors are back with a vengeance. I wonder if thats why the linting is not running as expected. We may have to wait until things are working again to re-trigger and see...

**Comment by lpantano** [comment]
@drpatelh , I think is ok now. The travis is passing, although I don't know why is not updating here. If the manifest seems ok to you, I can merge it.

**Comment by drpatelh** [comment]
Yep. Im happy if you are. Hopefully, you should be able to merge yourself now 👍

**Pull request merged**
