### PR TITLE
Add s3 data paths to test_full.config

### PR DESCRIPTION
**Pull request by ewels**
Setting up full size dataset testing - see #56

## PR checklist
 - [ ] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/smrnaseq branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/smrnaseq)
 - [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [ ] Make sure your code lints (`nf-core lint .`).
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

### CODE REVIEW

**Comment by ewels** [comment]
First stab at writing a config file for these files @lpantano but haven't tried to run this yet. I think the next step is to test it ourselves using `-profile test_full` to see if it works.

I wasn't sure if the harpin and mature fasta files are typically served from somewhere central?

**Comment by ewels** [comment]
Ok, with testing I found that a bunch of `params` are not initialised in `nextflow.config`, so I added what I found. This also meant that some weren't being picked up by `nf-core schema build`, so I reran that and added a missing parameter there.

**Comment by ewels** [comment]
Regarding `params.mirtrace_species`, the docs say:

> This is automatically set when using `--genome`. Example values: `hsa`, `mmu`...

In `main.nf` I can see that it's being set using an iGenomes config:
https://github.com/nf-core/smrnaseq/blob/3a0cb6ccc9143ca0766ffb5413671b01aa2433d4/main.nf#L83

However, the `mirtrace_species` value is not present in the [`igenomes.config`](https://github.com/nf-core/smrnaseq/blob/dev/conf/igenomes.config) file, so it won't do anything / work...

**Comment by ewels** [comment]
ok so following this further to try to fix, I am getting even more confused. This code is used to automatically download the miRBase reference:

https://github.com/nf-core/smrnaseq/blob/3a0cb6ccc9143ca0766ffb5413671b01aa2433d4/main.nf#L117-L118

But how is `hsa` specific enough? How does it know whether it's genome build GRCh37 or GRCh38 for example?

@lpantano can you help me out here please? 😰

**Comment by ewels** [comment]
Also, if we're downloading the GFF reference from miRBase like this, how come we can't also download the mature and hairpin fasta files in the same way? Would be good to add that, would make the pipeline a lot easier to run.

**Comment by lpantano** [comment]
I cannot say a lot about `mirtrace_species`. We need it for other tools as well, not only mirtrace thought. 

For the GTF, that is something I added, ideally should be added to the genomes file, so knowing the species and version it will autofill, but since that data is in S3 and I think we needed to coordinate to move all that to S3, I left it as you see now. Another option is to point everything to mirbase, but mirbase sometimes is down. 

For the GFF version question: GFF will be used to get coordinates of miRNA inside the precursor, so even if genome is one or another, and genome coordinates changes, the relative position inside the precursor will remain. So, it is not technical wrong, but I agree that it should match the version of the other references.

I would do this if we have space in S3:

Get a copy of mirbase to S3, and point the mirtrace_species, the precursors and the mirna and the gff to that place for each specie in igenome file. That would make things right I think. If this is a lot, we can point to mirbase for now as well. Happy to help on this.

**Comment by ewels** [comment]
ok, I've gone through all of the genomes in `conf/igenomes.config` and looked them up in [this KEGG Organisms list page](https://www.genome.jp/kegg/catalog/org_list.html) to find their organism code. I then looked at the [miRBase FTP](ftp://mirbase.org/pub/mirbase/CURRENT/) to see if that code existed. If it didn't, I still copied it in but left it as a code comment (in case we want organism codes for anything else in the future).

**Comment by ewels** [comment]
ok, and I have added to the `bowtie_indices` process some logic that checks the file extensions for the mature and hairpin FASTA files and runs `gunzip` if they end with `.gz`.

This allows us to set these parameters to the miRBase FTP URLs by default. Then if not ovewritten, the pipeline should try to download and stage the files. They will then be uncompressed and _should_ hopefully work as expected.

**Comment by ewels** [comment]
@lpantano - this approach is maybe not as good as syncing all of miRBase to AWS-iGenomes, as I appreciate that miRBase can be down sometimes. However, do you think that it's ok / sufficient? Syncing to AWS-iGenomes is a fairly large job..

**Comment by ewels** [comment]
ok and just did a fair bit of code cleanup in the pipeline initialisation code in that last commit. Deleted a bunch of stuff that I think was not meant to be there (eg. `params.gtf` which does not seem to be used or mentioned anywhere?). Hopefully I didn't break stuff. Would be fab if anyone could do some testing on this code (now or after merge to `dev`).

**Comment by ewels** [comment]
Approved via slack: https://nfcore.slack.com/archives/CL66GAJBF/p1605898538138000

**Pull request merged**
