### PR TITLE
Issue #175

### PR DESCRIPTION
**Pull request by BarryDigby**
#175

### CODE REVIEW

**Comment by lpantano** [comment]
I think this is good to me. Not sure why the conditional statements where there. @apeltzer , @JoseEspinosa , what do you think?

**Review by JoseEspinosa — COMMENTED** [review]
I am afraid that they can not be removed. 
The conditional statements avoid that when skipping a process using for instance the `skip_mirdeep` argument, warning such as the one below appear: 
```
WARN: There's no process matching config selector:
NFCORE_SMRNASEQ:SMRNASEQ:MIRDEEP2:MIRDEEP2_MAPPER
```
This means that any conditional statement in the workflow needs to have the same condition for the processes under the conditional statement in the `modules.config`.

**Comment by apeltzer** [comment]
Anything we can do then to fix #175 @JoseEspinosa ?

**Comment by lpantano** [comment]
maybe we can do this:

```
if (params.fasta | params.genome)
```

since any of these two parameters is going to need that file names change.

**Review by JoseEspinosa — COMMENTED** [review]
Yeah, probably @lpantano is correct, I did not test though.

**Comment by apeltzer** [comment]
Can you update he PR @BarryDigby ?

**Comment by BarryDigby** [comment]
@apeltzer Was this resolved in #184 ? Harshil seems to have removed the same lines of code I pointed out and "`Initialised params.fasta, params.mirtrace_species and params.bowtie_index in main.nf instead of smrnaseq.nf so their values are resolved properly when using a config file`" 

This PR may well be out of date by now, can delete it if necessary. 

https://github.com/nf-core/smrnaseq/pull/184/files#diff-bf809c928cb10b54d251dec8a140a2d5505150f97175d8d7b51dda9cc57971feL182-R208

**Comment by apeltzer** [comment]
I think you're probably right @BarryDigby  - then lets close and if the problem persists (mind to test `dev` ;-) ?) we can still resolve it later 👍🏻

**Pull request closed without merging**
