### PR TITLE
Change `.bai` index for `.csi` index in `samtools_index`

### LINKED ISSUE #132: Error because of large chromosomes
As part of the pipeline, Bowtie alignment files are indexed using samtools' BAI index. The problem is that the BAI index can only index chromosomes smaller than 512 Mbp. For larger chromosomes, a CSI index (also from samtools) needs to be used instead (it doesn't have a hardcoded limit). 

The marsupial opossum's chromosomes 1 and 2 are larger than 512 Mbp. The same is true for other marsupials and several plants.

Would it be possible to update the pipeline to use a CSI index instead of a BAI index? I realise the answer depends on the downstream tools that use the .bai file. If the .bai file is only required for samtools own use, the fix would be straightforward (using option -c when indexing the bam file with samtools).

### PR DESCRIPTION
**Pull request by atrigila**
Fixes #132 

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nf-test test main.nf.test -profile test,docker`).
- [x] `CHANGELOG.md` is updated.

### CODE REVIEW

**Review by apeltzer — APPROVED** [review]
That doesnt have any unforeseen side effects? In the past I sometimes had other tools using samtools indices that went awkward when being supplied with a CSI index. But ok, the tests run fine 👍🏻

**Review by nschcolnicov — APPROVED** [review]
LGTM

**Comment by nschcolnicov** [comment]
> That doesnt have any unforeseen side effects? In the past I sometimes had other tools using samtools indices that went awkward when being supplied with a CSI index. But ok, the tests run fine 👍🏻

I took a closer and it makes sense that the changes have no other impact.
Looking at the subworkflow "BAM_SORT_STATS_SAMTOOLS" script: The both the .csi or .bai files that are outputed are then combined with the .bam files channel and then used as input for "BAM_STATS_SAMTOOLS" which produces 3 stat files as output which we are validating with md5sums in the tests. But besides this, the .csi or .bai files emitted by "SAMTOOLS_SORT" are not used for anything else afterwards.

**Comment by apeltzer** [comment]
Cool then :)

**Pull request merged**
