### PR TITLE
fix multiqc error

### PR DESCRIPTION
**Pull request by lpantano**
this need to be fixed, to get the test running. TEMPLATE testing is failing due to that right now in local using the docker container.

### CODE REVIEW

**Comment by lpantano** [comment]
@drpatelh do you think that is fine to merge?

**Comment by drpatelh** [comment]
Are you trying to fix the tests for the PR below? Ive re-triggered the Travis tests to see if it was an intermittent issue.
https://github.com/nf-core/smrnaseq/pull/18

Never had to run tests for `TEMPLATE` before...this was added to the `rnaseq` pipeline too right? Dont see any harm in it.

**Comment by lpantano** [comment]
yes, it was added. Thank you!

**Comment by lpantano** [comment]
PS: I am not allow to merge it, sorry, whenever you have a chance

**Comment by drpatelh** [comment]
You should be able to merge this after approval...probably a GitHub setting that needs to be changed. Ive merged this one now but maybe we can try and play around with this for the next PR to give you merge rights.

**Comment by ewels** [comment]
Weird - you should be able to... You're a member of @nf-core/all and that team has write permissions on this repo...

**Pull request merged**
